apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

images:
  - name: wolfix1245/complex
    newTag: "23fa8600062db9d997678637c1dfa47d9b2df6ec"

commonLabels:
  environment: staging