apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingcomplex-app
  labels:
    app: landingcomplex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingcomplex-app
  template:
    metadata:
      labels:
        app: landingcomplex-app
    spec:
      containers:
        - name: landingcomplex-app
          image: wolfix1245/landing:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "1000Mi"
              ephemeral-storage: "1000Mi"
            limits:
              cpu: "1000m"
              memory: "1000Mi"
              ephemeral-storage: "2000Mi"