apiVersion: v1
kind: Service
metadata:
  name: landingcomplex-service
  labels:
    app: landingcomplex-app
spec:
  type: ClusterIP
  selector:
    app: landingcomplex-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP