apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex
  labels:
    app: complex
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: complex
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: complex
        name: complex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/production
                    operator: In
                    values:
                      - "worker-production"
      tolerations: []
      containers:
        - name: complex
          image: wolfix1245/complex:1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1000Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: JWT_SECRET
            - name: AI_DEEPSEEK_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: AI_DEEPSEEK_KEY
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30