apiVersion: v1
kind: Service
metadata:
  name: complex-service
  labels:
    app: complex
spec:
  type: ClusterIP
  selector:
    app: complex
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP