apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landingcomplex-ingress
spec:
  tls:
  - hosts:
    - dev.wolfixsite.shop
    secretName: landing-dev-tls
  rules:
  - host: dev.wolfixsite.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landingcomplex-service
            port:
              number: 80