apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - ingress-patch.yaml

images:
  - name: wolfix1245/landing
    newTag: "eac51a7f630a12899d2d38f61a2e11975f4532b4"

commonLabels:
  environment: development