apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userwebsite-ingress
  labels:
    app: userwebsite-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - userwebsite.wolfixsite.shop
    secretName: userwebsite-tls
  rules:
  - host: userwebsite.wolfixsite.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: userwebsite-service
            port:
              number: 80