apiVersion: v1
kind: Service
metadata:
  name: userwebsite-service
  labels:
    app: userwebsite-app
spec:
  type: ClusterIP
  selector:
    app: userwebsite-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP